#!/bin/bash
#SBATCH -J fastqc
#SBATCH -D /data/scratch/timaz/atac
#SBATCH -o out2.out
#SBATCH --partition=nowick
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=10G
#SBATCH --time=30-00:00:00
#SBATCH --mail-type=end
#SBATCH --mail-user=timaz@zedat.fu-berlin.de
multiqc results/fastqc/. 
